// Colors
#define            BLACK         0x0E
#define            BLACK_2       0x0D
#define            BLACK_3       0x0F
#define            BLACK_4       0x1D
#define            BLACK_5       0x1E
#define            BLACK_6       0x1F
#define            BLACK_7       0x2E
#define            BLACK_8       0x2F
#define            BLACK_9       0x3E
#define            BLACK_10      0x3F
#define       DARK_GRAY          0x00
#define       DARK_GRAY_2        0x2D
#define            GRAY          0x10
#define            GRAY_2        0x3D
#define      LIGHT_GRAY          0x20
#define            WHITE         0x30
#define       DARK_GRAY_BLUE     0x01
#define            GRAY_BLUE     0x11
#define      LIGHT_GRAY_BLUE     0x21
#define VERY_LIGHT_GRAY_BLUE     0x31
#define       DARK_BLUE          0x02
#define            BLUE          0x12
#define      LIGHT_BLUE          0x22
#define VERY_LIGHT_BLUE          0x32
#define       DARK_PURPLE        0x03
#define            PURPLE        0x13
#define      LIGHT_PURPLE        0x23
#define VERY_LIGHT_PURPLE        0x33
#define       DARK_PINK          0x04
#define            PINK          0x14
#define      LIGHT_PINK          0x24
#define VERY_LIGHT_PINK          0x34
#define       DARK_FUCHSIA       0x05
#define            FUCHSIA       0x15
#define      LIGHT_FUCHSIA       0x25
#define VERY_LIGHT_FUCHSIA       0x35
#define       DARK_RED           0x06
#define            RED           0x16
#define      LIGHT_RED           0x26
#define VERY_LIGHT_RED           0x36
#define       DARK_ORANGE        0x07
#define            ORANGE        0x17
#define      LIGHT_ORANGE        0x27
#define VERY_LIGHT_ORANGE        0x37
#define       DARK_TAN           0x08
#define            TAN           0x18
#define      LIGHT_TAN           0x28
#define VERY_LIGHT_TAN           0x38
#define       DARK_GREEN         0x09
#define            GREEN         0x19
#define      LIGHT_GREEN         0x29
#define VERY_LIGHT_GREEN         0x39
#define       DARK_LIME_GREEN    0x0A
#define            LIME_GREEN    0x1A
#define      LIGHT_LIME_GREEN    0x2A
#define VERY_LIGHT_LIME_GREEN    0x3A
#define       DARK_SEAFOAM_GREEN 0x0B
#define            SEAFOAM_GREEN 0x1B
#define      LIGHT_SEAFOAM_GREEN 0x2B
#define VERY_LIGHT_SEAFOAM_GREEN 0x3B
#define       DARK_CYAN          0x0C
#define            CYAN          0x1C
#define      LIGHT_CYAN          0x2C
#define VERY_LIGHT_CYAN          0x3C
